language: node_js
sudo: false
node_js:
- 7
- 6
- 5
- 4
- '0.12'
- iojs
matrix:
after_success: NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha
  --report lcovonly -- -R spec --timeout 15000 "./test/**/*.test.js" && cat ./coverage/lcov.info
  | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
env:
  global:
  - secure: hpxf7obBI8eUCIDDwYn0eEXtgrobdkL8EWW7A1u0Us5vuJK6R8spETU0f4qmmv+GUDm7YxM7HRPOBMeoi/uiB475IvnDOen7kA76g1rQBMXemhJWFrnB1JizKzb1bQBe15ZtKwj6RdZkTK2jpMgtehecrsFI5M/bFPBKz75nd4Q=
  - secure: kUaJjK1l+A/x1LnTscwzOYdBaFekJ+wv6AQtYXmOiz3SPPDTbizD+pLUs+ZRBvWi2D5e6LivvBKLoOn5mvr/KSip0hriTCBwfjK+Sx8+kreXUv+gZXX+gCd37CCpp5PuOba0nErwNn3TAV3tCnMkUp0wxFnOdREXeCFv/qYEzGo=
deploy:
  provider: npm
  email: as.us.labs@sungardas.com
  api_key:
    secure: IafCsbxGASncqJ1b90lR91bbGqyUoO5ljuJRab+qvQenJafts7LAFeaYxpT0o8eRFZYwsJwAjJeqV1S8NcT4/Dz6NAbi2b3+f1qY0viXk2rWyZhHWgPjMKOQFTw2tEhbkAW2hMYf6YvAW087hnrXUVXQqlcw/p39EzN8WYxAIe8=
  on:
    tags: true
    repo: SungardAS/condensation
    node: 6
notifications:
  slack: sgaslabs-community:9fV0wYOO1bUrVhEcGNCwlkY6
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fdcdbf8972142ab62e53
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
